[book]
authors = ["Hilmar Gústafsson"]
language = "en"
multilingual = false
src = "src"
title = "Notes at Aalborg University"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[output.html]
# additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 0