name: github pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Download CLI
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: badboy/mdbook-mermaid
        tag: '0.2.2'
        path: /usr/local/bin
        file: mdbook-mermaid-0.2.2-x86_64-unknown-linux-gnu.tar.gz
        

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.3.5'

    - run: mdbook build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./book
